### ISSUE TITLE
woff2 错误，abort(TypeError: Failed to parse URL from /workspaces/font-server/api/temp/woff2/woff2.wasm) at Error

### ISSUE THREAD

**Issue by KonghaYao** [KonghaYao/cn-font-split#4]
abort(TypeError: Failed to parse URL from /workspaces/font-server/api/temp/woff2/woff2.wasm) at Error
    at jsStackTrace (/workspaces/font-server/api/temp/woff2/woff2.cjs:1037:23)
    at stackTrace (/workspaces/font-server/api/temp/woff2/woff2.cjs:1051:22)
    at process.abort (/workspaces/font-server/api/temp/woff2/woff2.cjs:814:54)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by KonghaYao** [comment]
请在你的代码的某一处把 fetch 函数给弄没😂
```js
/** node 在某一个版本新加的 api 导致库的环境判断失误，会BUG */
(globalThis as any).fetch = null;
```
